version: '3.5'

services:
  webserver:
    container_name: webserver
    build: './webserver'
    networks:
      - frontend
      - backend
    links:
      - database
    depends_on: 
      database:
        condition: service_healthy
    environment:
      WAIT_HOSTS: database:3306
    restart: always
    ports:
      - 80:80
    volumes:
      - ./DocumentRoot:/var/www/html
    command: bash -c 'cd /var/www/html && php artisan migrate:fresh --seed && php artisan serve --host=0.0.0.0 --port=80'

  database:
    container_name: database
    image: mariadb:latest
    environment: 
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER: test
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: test

    networks: 
      - backend
    restart: always
    ports: 
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: "mysql -utest -p1234 --execute \"SHOW DATABASES;\" && echo 'Datbase OK!'"
      timeout: 15s
      retries: 3

networks:
  frontend:
  backend:
